FROM node:22-alpine

# Set working directory
WORKDIR /app/Backend

# Install dependencies

COPY package.json package.json
COPY package-lock.json package-lock.json

RUN npm install

# Copy backend source code

COPY . .

# Expose the backend port

EXPOSE 3000


CMD [ "npm", "run", "dev" ]