name: Pulls and Deployment 
on:
  workflow_run:
    workflows: ["Build and Pushes Docker Images"]
    types:
      - completed



jobs:
  deploy: 
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v1
        with: 
          host: ${{secrets.SERVER_IP}}
          username: dhanraj
          key: ${{secrets.SERVER_SSH_KEY}}

          script: |
            DEPLOY_DIR = ~/simple-testing-app
            
            # -------------Create deployment directory if it doesn't exist------------------

            if [ ! -d "$DEPLOY_DIR" ]; then
              echo "Deployment directory does not exist. Creating..."
              mkdir -p $DEPLOY_DIR
            fi
            
            # -------------Navigate to deployment directory------------------

            cd $DEPLOY_DIR
            echo "downloading docker compose file..."

            # -------------Downloading the Docker compose file------------------

            curl -O https://raw.githubusercontent.com/dhanraj11/simple-testing-app/main/docker-compose.prod.yml

            # -------------Pulling the latest images------------------

            docker-compose -f docker-compose.prod.yml pull
            echo "Pulled latest images."

            # -------------Starting the containers------------------

            docker-compose -f docker-compose.prod.yml up -d  --remove-orphans
            echo "Deployment completed successfully."


            # -------------Cleaning up old images------------------
            docker image prune -af




            
    
